spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
  application:
    name: item-api
  datasource:
    url: jdbc:mysql://localhost:3307/items?allowPublicKeyRetrieval=true&useSSL=FALSE
    username: user
    password: user
    driverClassName: com.mysql.cj.jdbc.Driver

server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${random.value}

