spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: item-api
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: user
    password: user

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${random.value}